/* eslint-disable */
// @ts-nocheck
// This file will be auto-generated by TanStack Router
// For now, we define it manually with all routes

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as LoginRoute } from './routes/login'
import { Route as RegisterRoute } from './routes/register'
import { Route as TrainingIndexRoute } from './routes/training/index'
import { Route as TrainingModuleRoute } from './routes/training/$moduleId'
import { Route as MachinesIndexRoute } from './routes/machines/index'
import { Route as MachineDetailRoute } from './routes/machines/$machineId'
import { Route as MachineReserveRoute } from './routes/machines/$machineId.reserve'
import { Route as ReservationsIndexRoute } from './routes/reservations/index'
import { Route as AdminCheckoutsRoute } from './routes/admin/checkouts'
import { Route as AdminCheckoutsUserRoute } from './routes/admin/checkouts.$userId'
import { Route as AdminMachinesRoute } from './routes/admin/machines'
import { Route as AdminMachineEditRoute } from './routes/admin/machines.$machineId'
import { Route as AdminTrainingRoute } from './routes/admin/training'
import { Route as AdminUsersRoute } from './routes/admin/users'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRoute
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRoute
      parentRoute: typeof rootRoute
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingIndexRoute
      parentRoute: typeof rootRoute
    }
    '/training/$moduleId': {
      id: '/training/$moduleId'
      path: '/training/$moduleId'
      fullPath: '/training/$moduleId'
      preLoaderRoute: typeof TrainingModuleRoute
      parentRoute: typeof rootRoute
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesIndexRoute
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachineDetailRoute
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/reserve': {
      id: '/machines/$machineId/reserve'
      path: '/machines/$machineId/reserve'
      fullPath: '/machines/$machineId/reserve'
      preLoaderRoute: typeof MachineReserveRoute
      parentRoute: typeof rootRoute
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsIndexRoute
      parentRoute: typeof rootRoute
    }
    '/admin/checkouts': {
      id: '/admin/checkouts'
      path: '/admin/checkouts'
      fullPath: '/admin/checkouts'
      preLoaderRoute: typeof AdminCheckoutsRoute
      parentRoute: typeof rootRoute
    }
    '/admin/checkouts/$userId': {
      id: '/admin/checkouts/$userId'
      path: '/admin/checkouts/$userId'
      fullPath: '/admin/checkouts/$userId'
      preLoaderRoute: typeof AdminCheckoutsUserRoute
      parentRoute: typeof rootRoute
    }
    '/admin/machines': {
      id: '/admin/machines'
      path: '/admin/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesRoute
      parentRoute: typeof rootRoute
    }
    '/admin/machines/$machineId': {
      id: '/admin/machines/$machineId'
      path: '/admin/machines/$machineId'
      fullPath: '/admin/machines/$machineId'
      preLoaderRoute: typeof AdminMachineEditRoute
      parentRoute: typeof rootRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRoute
      parentRoute: typeof rootRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  TrainingIndexRoute,
  TrainingModuleRoute,
  MachinesIndexRoute,
  MachineDetailRoute,
  MachineReserveRoute,
  ReservationsIndexRoute,
  AdminCheckoutsRoute,
  AdminCheckoutsUserRoute,
  AdminMachinesRoute,
  AdminMachineEditRoute,
  AdminTrainingRoute,
  AdminUsersRoute,
])
