/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as MachinesIndexRouteImport } from './routes/machines/index'
import { Route as TrainingModuleIdRouteImport } from './routes/training/$moduleId'
import { Route as MachinesMachineIdRouteImport } from './routes/machines/$machineId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as AdminMachinesRouteImport } from './routes/admin/machines'
import { Route as AdminCheckoutsRouteImport } from './routes/admin/checkouts'
import { Route as MachinesMachineIdReserveRouteImport } from './routes/machines/$machineId.reserve'
import { Route as ApiWebhooksCalcomRouteImport } from './routes/api/webhooks.calcom'
import { Route as ApiSseBookingsRouteImport } from './routes/api/sse.bookings'
import { Route as AdminMachinesMachineIdRouteImport } from './routes/admin/machines.$machineId'
import { Route as AdminCheckoutsUserIdRouteImport } from './routes/admin/checkouts.$userId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingModuleIdRoute = TrainingModuleIdRouteImport.update({
  id: '/training/$moduleId',
  path: '/training/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/admin/training',
  path: '/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMachinesRoute = AdminMachinesRouteImport.update({
  id: '/admin/machines',
  path: '/admin/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckoutsRoute = AdminCheckoutsRouteImport.update({
  id: '/admin/checkouts',
  path: '/admin/checkouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdReserveRoute =
  MachinesMachineIdReserveRouteImport.update({
    id: '/reserve',
    path: '/reserve',
    getParentRoute: () => MachinesMachineIdRoute,
  } as any)
const ApiWebhooksCalcomRoute = ApiWebhooksCalcomRouteImport.update({
  id: '/api/webhooks/calcom',
  path: '/api/webhooks/calcom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSseBookingsRoute = ApiSseBookingsRouteImport.update({
  id: '/api/sse/bookings',
  path: '/api/sse/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMachinesMachineIdRoute = AdminMachinesMachineIdRouteImport.update({
  id: '/$machineId',
  path: '/$machineId',
  getParentRoute: () => AdminMachinesRoute,
} as any)
const AdminCheckoutsUserIdRoute = AdminCheckoutsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminCheckoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/checkouts': typeof AdminCheckoutsRouteWithChildren
  '/admin/machines': typeof AdminMachinesRouteWithChildren
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/machines/': typeof MachinesIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/admin/checkouts/$userId': typeof AdminCheckoutsUserIdRoute
  '/admin/machines/$machineId': typeof AdminMachinesMachineIdRoute
  '/api/sse/bookings': typeof ApiSseBookingsRoute
  '/api/webhooks/calcom': typeof ApiWebhooksCalcomRoute
  '/machines/$machineId/reserve': typeof MachinesMachineIdReserveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/checkouts': typeof AdminCheckoutsRouteWithChildren
  '/admin/machines': typeof AdminMachinesRouteWithChildren
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/machines': typeof MachinesIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/training': typeof TrainingIndexRoute
  '/admin/checkouts/$userId': typeof AdminCheckoutsUserIdRoute
  '/admin/machines/$machineId': typeof AdminMachinesMachineIdRoute
  '/api/sse/bookings': typeof ApiSseBookingsRoute
  '/api/webhooks/calcom': typeof ApiWebhooksCalcomRoute
  '/machines/$machineId/reserve': typeof MachinesMachineIdReserveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/checkouts': typeof AdminCheckoutsRouteWithChildren
  '/admin/machines': typeof AdminMachinesRouteWithChildren
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/machines/': typeof MachinesIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/admin/checkouts/$userId': typeof AdminCheckoutsUserIdRoute
  '/admin/machines/$machineId': typeof AdminMachinesMachineIdRoute
  '/api/sse/bookings': typeof ApiSseBookingsRoute
  '/api/webhooks/calcom': typeof ApiWebhooksCalcomRoute
  '/machines/$machineId/reserve': typeof MachinesMachineIdReserveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/checkouts'
    | '/admin/machines'
    | '/admin/training'
    | '/admin/users'
    | '/machines/$machineId'
    | '/training/$moduleId'
    | '/machines/'
    | '/reservations/'
    | '/training/'
    | '/admin/checkouts/$userId'
    | '/admin/machines/$machineId'
    | '/api/sse/bookings'
    | '/api/webhooks/calcom'
    | '/machines/$machineId/reserve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/checkouts'
    | '/admin/machines'
    | '/admin/training'
    | '/admin/users'
    | '/machines/$machineId'
    | '/training/$moduleId'
    | '/machines'
    | '/reservations'
    | '/training'
    | '/admin/checkouts/$userId'
    | '/admin/machines/$machineId'
    | '/api/sse/bookings'
    | '/api/webhooks/calcom'
    | '/machines/$machineId/reserve'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/checkouts'
    | '/admin/machines'
    | '/admin/training'
    | '/admin/users'
    | '/machines/$machineId'
    | '/training/$moduleId'
    | '/machines/'
    | '/reservations/'
    | '/training/'
    | '/admin/checkouts/$userId'
    | '/admin/machines/$machineId'
    | '/api/sse/bookings'
    | '/api/webhooks/calcom'
    | '/machines/$machineId/reserve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminCheckoutsRoute: typeof AdminCheckoutsRouteWithChildren
  AdminMachinesRoute: typeof AdminMachinesRouteWithChildren
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRouteWithChildren
  TrainingModuleIdRoute: typeof TrainingModuleIdRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  ApiSseBookingsRoute: typeof ApiSseBookingsRoute
  ApiWebhooksCalcomRoute: typeof ApiWebhooksCalcomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$moduleId': {
      id: '/training/$moduleId'
      path: '/training/$moduleId'
      fullPath: '/training/$moduleId'
      preLoaderRoute: typeof TrainingModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/machines': {
      id: '/admin/machines'
      path: '/admin/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkouts': {
      id: '/admin/checkouts'
      path: '/admin/checkouts'
      fullPath: '/admin/checkouts'
      preLoaderRoute: typeof AdminCheckoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId/reserve': {
      id: '/machines/$machineId/reserve'
      path: '/reserve'
      fullPath: '/machines/$machineId/reserve'
      preLoaderRoute: typeof MachinesMachineIdReserveRouteImport
      parentRoute: typeof MachinesMachineIdRoute
    }
    '/api/webhooks/calcom': {
      id: '/api/webhooks/calcom'
      path: '/api/webhooks/calcom'
      fullPath: '/api/webhooks/calcom'
      preLoaderRoute: typeof ApiWebhooksCalcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sse/bookings': {
      id: '/api/sse/bookings'
      path: '/api/sse/bookings'
      fullPath: '/api/sse/bookings'
      preLoaderRoute: typeof ApiSseBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/machines/$machineId': {
      id: '/admin/machines/$machineId'
      path: '/$machineId'
      fullPath: '/admin/machines/$machineId'
      preLoaderRoute: typeof AdminMachinesMachineIdRouteImport
      parentRoute: typeof AdminMachinesRoute
    }
    '/admin/checkouts/$userId': {
      id: '/admin/checkouts/$userId'
      path: '/$userId'
      fullPath: '/admin/checkouts/$userId'
      preLoaderRoute: typeof AdminCheckoutsUserIdRouteImport
      parentRoute: typeof AdminCheckoutsRoute
    }
  }
}

interface AdminCheckoutsRouteChildren {
  AdminCheckoutsUserIdRoute: typeof AdminCheckoutsUserIdRoute
}

const AdminCheckoutsRouteChildren: AdminCheckoutsRouteChildren = {
  AdminCheckoutsUserIdRoute: AdminCheckoutsUserIdRoute,
}

const AdminCheckoutsRouteWithChildren = AdminCheckoutsRoute._addFileChildren(
  AdminCheckoutsRouteChildren,
)

interface AdminMachinesRouteChildren {
  AdminMachinesMachineIdRoute: typeof AdminMachinesMachineIdRoute
}

const AdminMachinesRouteChildren: AdminMachinesRouteChildren = {
  AdminMachinesMachineIdRoute: AdminMachinesMachineIdRoute,
}

const AdminMachinesRouteWithChildren = AdminMachinesRoute._addFileChildren(
  AdminMachinesRouteChildren,
)

interface MachinesMachineIdRouteChildren {
  MachinesMachineIdReserveRoute: typeof MachinesMachineIdReserveRoute
}

const MachinesMachineIdRouteChildren: MachinesMachineIdRouteChildren = {
  MachinesMachineIdReserveRoute: MachinesMachineIdReserveRoute,
}

const MachinesMachineIdRouteWithChildren =
  MachinesMachineIdRoute._addFileChildren(MachinesMachineIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminCheckoutsRoute: AdminCheckoutsRouteWithChildren,
  AdminMachinesRoute: AdminMachinesRouteWithChildren,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminUsersRoute: AdminUsersRoute,
  MachinesMachineIdRoute: MachinesMachineIdRouteWithChildren,
  TrainingModuleIdRoute: TrainingModuleIdRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  ApiSseBookingsRoute: ApiSseBookingsRoute,
  ApiWebhooksCalcomRoute: ApiWebhooksCalcomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
